### ISSUE TITLE
Create Scrutinizer configuration

### ISSUE THREAD

**Issue by franzliedke** [franzliedke/studio#10]
Scrutinizer seems to be a much-used tool with many Composer libraries, so we may as well offer an integration.

**Comment by RemiCollin** [comment]
Scrutinizer doesn't need any specific file in your package to work. You just drop the path to your repo in the app and you're done.

**Comment by franzliedke** [comment]
What about `.scrutinizer.yml`?

**Comment by RemiCollin** [comment]
it's optional
