### ISSUE TITLE
Add support for Composer 2

### ISSUE THREAD

**Issue by baukevdw** [franzliedke/studio#101]
Composer 2.0 is getting closer to a stable release and plugin authors are asked to test Composer 2 and add support to the plugins.

For more information see:
https://github.com/composer/composer/issues/8726

If I've got time I'll take a look into it.

**Comment by ouun** [comment]
The only reason I do not update to Composer v2 is the uncertain Studio support.

**Comment by rask** [comment]
> The "franzl/studio" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.

**Comment by buznablaster** [comment]
Well, the plugin quite works with the composer 2 version if you apply the already proposed pull request https://github.com/franzliedke/studio/pull/104. There is an issue with the canonical repos though so be aware of it, but for development of a concrete package, it should be fine.

**Comment by vikingmaster** [comment]
This library is a must use for modularized applications and package development, the community needs it.
@franzliedke can we get some information how to progress the support for Composer 2?

**Comment by franzliedke** [comment]
Hello everyone, I'm [looking for people](https://github.com/franzliedke/studio/pull/104#issuecomment-733266424) to pair with me on getting this ready for Composer 2. :smiley:

**Comment by franzliedke** [comment]
Relased in [version 0.15.0](https://github.com/franzliedke/studio/releases/tag/0.15.0). Please update and let me know if you encounter any problems.
