### ISSUE TITLE
Namespace issue

### ISSUE THREAD

**Issue by kevinirlen** [franzliedke/studio#118]
Hi,

Thanks for this package. I tried using this with a Symfony app. But I'm getting this error after telling studio to load my package.

```
Attempted to load class "TipUserBundle" from namespace "Tip\UserBundle".
Did you forget a "use" statement for another namespace?
```

Any ideas?

**Comment by franzliedke** [comment]
Hi,

from your report, I fail to see the relation to Studio. Can you explain in more detail what it is you're trying to do / provide a minimal reproduction example, please?

**Comment by kevinirlen** [comment]
Hmm ok, turns out i'm an idiot.. This issue is not related to studio. I'll explain my problem and give the solution if other symfony dev encounter this issue..

The thing is, i'm using docker.. and the solution to fix this issue, is to simply mount the folder of the packages as volumes inside docker.

```
        volumes:
            - "../../../bundles:/var/www/bundles"
```

You might want to double check your path.. :) I'm closing this issue..

**Comment by franzliedke** [comment]
Happens to the best of us. 🤗
