### ISSUE TITLE
Studio package autoload.php require once got printed behind return statement

### ISSUE THREAD

**Issue by maartenscholz** [franzliedke/studio#13]
In my main projects autoload.php the generated require of my studio package autoload.php gets printed behind the return statement, rendering it moot.
```php
return ComposerAutoloaderInite73ad39f6603d8c0d4afc6ca2622bde4::getLoader();

// @generated by Composer Studio (https://github.com/franzliedke/studio)
require_once __DIR__ . '/../laravel-queue/vendor/autoload.php';
```
I had to manually move it above the return statement for it to work but each composer dump resets that.

**Comment by franzliedke** [comment]
Wow, ahem, way to overlook something. Thanks for the report, will fix it immediately.

**Comment by franzliedke** [comment]
Okay, this is part of [v0.9.5](https://github.com/franzliedke/studio/releases/tag/0.9.5) which was just released. =)

**Comment by maartenscholz** [comment]
Fast :) thanks!
