### ISSUE TITLE
[Proposal] studio dump-autoload

### ISSUE THREAD

**Issue by vluzrmos** [franzliedke/studio#22]
After doing a `composer dump-autoload` it refreshes the `vendor/autoload.php` of the root application, and that removes the autoload of the package created by <b>studio</b>.

I know there is a solution for that, its create a "post-autload-dump" on composer.json of my application, but it is annoying.

**Comment by juliobitencourt** [comment]
👍

**Comment by vluzrmos** [comment]
Sorry for that, that issue was happening because my local machine has Studio, but my Virtual Machine (Homestead) doens't. When I run `composer dump-autoload` on VM, it refreshes the `vendor/autoload.php`.

**Comment by franzliedke** [comment]
Glad you found the solution.
