### ISSUE TITLE
Can I change location where Studio creates packages?

### ISSUE THREAD

**Issue by tomicakorac** [franzliedke/studio#27]
Hi, I know this is more of a support question than an issue, but I'm not aware of any other way to ask. So, by default, Studio creates packages in `/root/vendor-name/package-name`. Is it possible to have Studio create all the packeges inside, let's say, `/root/studio/vendor-name/package-name`, but without having the `studio` segment in the package's namespace, because obviously once I publish the package, the `studio` segment will not be there.

**Comment by franzliedke** [comment]
Hey, sorry for getting back only now.

When running `studio create foo`, "foo" is the path where the new package will be created - that should do the trick, no?

**Comment by tomicakorac** [comment]
Yes, but won't that permanently add `foo` to my plugins namespace? Here's what I'm aiming at. I want to create a `/workbench` directory inside Laravel root, and keep all packages in development there. Once they're finished, I want to publish them, but I don't want them to keep the `\Workbench\` segment in their namespace. Is this possible right now when I use `studio create workbench/package`?

**Comment by franzliedke** [comment]
Hey, sorry for being a little slow again...

Yes, it will ask for the namespace to use. It will suggest a namespace based on the path, but you'll be able to override it.

**Comment by tomicakorac** [comment]
Sorry for being a pain, but how can I override it? Can you please give an example?

**Comment by franzliedke** [comment]
Huh? When running `studio create workbench/foo`, it will ask you a series of questions, starting with the name of the package. One of them will ask for the namespace, which you will be able to modify.

**Comment by tomicakorac** [comment]
Oh... I feel very bad now for asking a question to which you've answered even in the documentation. Thank you very much for your patience. And for the great work with Studio!

**Comment by franzliedke** [comment]
Haha, no problem. I was worried I was misunderstanding something, but oh well. Glad we got it sorted.

And thanks. :)
