### ISSUE TITLE
Autoload files

### ISSUE THREAD

**Issue by tobscure** [franzliedke/studio#29]
Studio currently doesn't autoload files from the packages that it manages. See https://github.com/franzliedke/studio/blob/master/src/Composer/StudioPlugin.php#L55

In Flarum we have some temporary code (in bootstrap.php) to work around this by loading the files we need manually.

Just creating an issue so this doesn't get forgotten :)

**Comment by franzliedke** [comment]
I just pushed [a commit](https://github.com/franzliedke/studio/commit/75ef184899dd34451b03f81c3e75fff1f0dbf9ba) that should fix this issue.

Managed packages will not be hacked into the autoloader files anymore, but instead they will be symlinked into the vendor dir. Composer already provides this for free using [path repositories](https://getcomposer.org/doc/05-repositories.md#path). :)
