### ISSUE TITLE
Load required packages on composers update

### ISSUE THREAD

**Issue by stefro** [franzliedke/studio#34]
Hi,

In one of the packages I'm creating (let's call this foo/bar) I require other packages in the composer.json file like this:
```
    "require": {
        "demo/baz": "^1.0",
    },
```
When I call `composer update` on the main project the package demo/baz will not be loaded.

However (this is intesting), when I add foo/bar to a new (different) project so it gets loaded throug the main composer.json file and placed in the vendor directory. Then, demo/baz does get loaded!

So I think it has got something to do with the way studio loads the foo/bar package.

Any help is appreciated!

**Comment by tobscure** [comment]
The way studio works is that you run the `composer install` command in each of your sub-project folders (i.e. foo/bar), and then studio will merge the autoloaders from those sub-projects into the parent project's autoloader.

**Comment by franzliedke** [comment]
Hmm, we should probably run `composer install` for the subpackages when doing it in the main package.

@stefro If you are running the latest dev-master version of Studio, a simple `composer dump-autoload` after the `composer update` should fix it.

**Comment by stefro** [comment]
@franzliedke and @tobscure 
Thanks guys! I'm running the dev-master now and it looks like everything is working fine.
Here is why I was confused at first: I was looking in the vendor dir of the root of my laravel application for the installed packages. Could not see them in here. Now I know they're installed in the vendor dir of the package itself.

Thanks!
