### ISSUE TITLE
No way to do a package publish?

### ISSUE THREAD

**Issue by simonberger** [franzliedke/studio#35]
I hoped to miss something but somehow I see no way to publish the package public folder like I could do in L4 - php artisan asset:publish --bench.

Nothing be published with php artisan vendor:publish either.

**Comment by nickescobedo** [comment]
Is this package intended to be for only Laravel or PHP in general? If it's PHP in general those commands probably wouldn't exist.

**Comment by simonberger** [comment]
Indeed the readme isn't clear on the goal of this. But it uses many symfony and/or laravel packages inside and I am not sure this really can be used for something else.
Also he did lot of promotion in laravel forums.
Anyway in my opinion there has to be a possibility to publish with this to really being a serious replacement of the old workbench functionality. Best would be to work with normal vendor:publish.

**Comment by tomicakorac** [comment]
Correct me if I'm mistaking, but isn't Laravel's `php artisan vendor:publish` (or `php artisan asset:publish`) command meant to publish only assets of the packages found in the `vendor` directory (and in the older versions also in the `workbench` directory)?

This library (Studio) is not intended to be used only in Laravel, nor in Symphony projects. The readme is quite clear on that. Studio's purpose is to build PHP packages for any kind of project, so it can't know about Laravel's specific functionalities.

However, Laravel documentation does give you a way to do `asset:publish` or `vendor:publish` on packages in a custom location. The exact method depends on the version of Laravel you're using, and you also need to add a `publishes` method to your package's Service Provider, and then you can simply run:

    php artisan vendor:publish --provider="Vendor\Package\ServiceProvider"

Please refer to [Laravel's documentation](http://laravel.com/docs/5.1/packages#publishing-file-groups) for more details on this.

**Comment by simonberger** [comment]
Thank you for your comment.
I understood the intention of this package. I just had a look at the requirements and it needs many symfony packages which I wouldn't want in a completely different environment. But maybe the job it does works well there too.
Anyway. I now got it to work. Somehow not with the provider argument. But It publishes with like a normally loaded vendor.
```
php artisan vendor:publish
```
after setting everything up correctly.

```
Copied Directory [/workbench/foo/bar/public] To [/public/foo/bar/package]
Publishing complete for tag []!
```

**Comment by franzliedke** [comment]
Hi there. I'm glad you got this working. :)

I've been a little quite lately; that's because I'm about to finish my master's thesis. Once that is done (next week), I plan to improve the README and the usage of this package dramatically.

**Comment by tomicakorac** [comment]
@franzliedke keep rocking! What's your thesis about, if it's no secret? :)

**Comment by franzliedke** [comment]
Any arbitrary combination of the buzzwords "components", "service orientation", "single page application" and some others. Basically rewriting the frontend of a large service-oriented application with SPA and rambling about architecture. :)
