### ISSUE TITLE
Support composer installers?

### ISSUE THREAD

**Issue by zxaos** [franzliedke/studio#36]
Right now, if you try to manage a package that composer should be placing somewhere other than vendor (using https://github.com/composer/installers ), studio still drops the package in the root directory. This doesn't make sense for packages that _must_ be installed to specific locations to function.

**Comment by franzliedke** [comment]
Which version are you using?

**Comment by zxaos** [comment]
0.9.5

**Comment by franzliedke** [comment]
This will work very well in the next release.
