### ISSUE TITLE
Check existence before loading package

### ISSUE THREAD

**Issue by simonberger** [franzliedke/studio#38]
If you try to load a non existenance package or just type a wrong path you get plenty of scary warnings and I am still not completely sure if it maybe wrote any autoloader entry or did something else.
There should be a check and a reasonable error message instead.

**Comment by franzliedke** [comment]
Thanks for your reports! I'll fix them in the next release. :)

**Comment by franzliedke** [comment]
Thanks again, I fixed it. Will be released very soon.
