### ISSUE TITLE
Unload package / Note of deleting

### ISSUE THREAD

**Issue by simonberger** [franzliedke/studio#39]
I do not like the delete functionality of scrap. The name may hint it but isn't clear.
I had to clone a package again in the beginning because it deleted all files while I just wanted to unload the package.

Maybe it's a personal thing but in my opinion there shouldn't be a deletion of the files, but just an unload of the package (just reversing what it does on load).
If you guys think its correct I still would suggest an additional comment named unload which does that.

**Comment by franzliedke** [comment]
Okay, I just [fixed this](https://github.com/franzliedke/studio/commit/61bcc3eebca95d60bef30aa7bfc37a93754a02f4) by adding a fat warning message before asking for confirmation. That should be good enough, right?

This will be included in the next stable release (v1.0) - we're just waiting for a pull request to Composer being merged.
