### ISSUE TITLE
Composer Plugin API requirement

### ISSUE THREAD

**Issue by sumityadav** [franzliedke/studio#43]
I have started to see the following warning:

```
The "franzl/studio" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).
```

**Comment by franzliedke** [comment]
This is already fixed in master.

**Comment by sumityadav** [comment]
Can you tag the release that contains the fix?

**Comment by franzliedke** [comment]
The other changes are not yet stable, unfortunately.

**Comment by c33s** [comment]
can't you just release a new tagged version with just this dependency error fixed? (this will also prevent users from spanning new tickets about this issue here)
