### ISSUE TITLE
Any supports for symfony/finder ~3.0

### ISSUE THREAD

**Issue by jcornil** [franzliedke/studio#44]
I get this error when I try to install franzl/studio.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for franzl/studio ^0.9.5 -> satisfiable by franzl/studio[0.9.5].
    - Conclusion: remove symfony/finder v3.0.1
    - Conclusion: don't install symfony/finder v3.0.1
   .
   .
   .

**Comment by franzliedke** [comment]
Thanks for the report, I've [done this in the master branch](https://github.com/franzliedke/studio/commit/c9aba9e08547e52cc4b99c925fc6018fb33f5fd1). 

It will still take a bit of time to get to the next release, though...
