### ISSUE TITLE
Recursive dependencies between studio packages

### ISSUE THREAD

**Issue by RemiCollin** [franzliedke/studio#45]
I have a project where I develop several composer packages with studio. Let's say I have a A, B, C package, all handled by studio. Packages A & B depends on C. The problem is, when autoloading, the C package isn't autoloaded from its own folder, but from the vendor directory of the A package. Is there an easy way to workaround this ?

**Comment by franzliedke** [comment]
Nope, but these kind of edge cases will be fixed in the next version. :)

**Comment by RemiCollin** [comment]
Great! Looking forward to it!
