### ISSUE TITLE
Error creating symlink on windows machine running vagrant

### ISSUE THREAD

**Issue by jonnywilliamson** [franzliedke/studio#57]
So I use a vagrant box (homestead) to do my development on windows 10.

This allows me to have a linux box, install all my libraries/code etc and still be able to develop on my windows machine using the shared folder feature of virtualbox.

However I have discovered an issue that when trying to use studio, the ability to create a symlink during the installation process fails.

![image](https://cloud.githubusercontent.com/assets/2513663/14456561/671f14da-009d-11e6-85e1-70961e9836b0.png)

The reason for this seems fairly complicated and probably is a mixture of many of these links - here is a small sample:
https://www.virtualbox.org/ticket/10085
https://github.com/mitchellh/vagrant/issues/6024
https://github.com/mitchellh/vagrant/issues/6188

I managed to work around this at the moment by a simple fix. Basically halt your virtual machine (`vagrant halt`). Close and command prompt you might have been using and then reopen your command prompt AS AN ADMINISTRATOR.

Then, simply `vagrant up` again and try it again. It should work.

For info I'm using
Windows 10
Vagrant 1.7.4
Virtual Box 5.0.10

**Comment by franzliedke** [comment]
Does this work for you, too?

~~~rb
config.vm.synced_folder "/projectfolder/www", "/var/www", type: "smb", mount_options: ["vers=3.02","mfsymlinks"]
~~~

**Comment by jonnywilliamson** [comment]
If you update to the latest version of homestead, this is already included if you set your shared folders to smb

See: https://github.com/laravel/homestead/commit/25f6b9881e7ff2b81a1d90dfdc5ce2aded8c6a1f


However, if you try and start the VM up again WITHOUT running it as admin, you get this message:

>SMB shared folders require running Vagrant with administrative
>privileges. This is a limitation of Windows, since creating new
>network shares requires admin privileges. Please try again in a
>console with proper permissions or use another synced folder type.

So it's kind of pointless for me I think.

It works if I run vagrant as admin and do not have folders set to smb.

If I use smb and add those new mount options, I HAVE to run vagrant as admin otherwise it will not boot up....therefore...why bother?

**Comment by franzliedke** [comment]
Okay, well, since it's not really a Studio issue, and there seem to be workarounds, I will close this.
