### ISSUE TITLE
Not Enough Arguments

### ISSUE THREAD

**Issue by ghprod** [franzliedke/studio#59]
Hi Franz, 

when on the last step creating a package, I get this error

![image](https://cloud.githubusercontent.com/assets/1922652/14515938/8f4fa280-0228-11e6-93c8-8dcc4f5298a7.png)

Do you have any idea?

Thanks

**Comment by franzliedke** [comment]
Hey, sorry to hear that. :(

Two questions:
- What is the exact command you're running?
- Which version of Studio are you using?

**Comment by ghprod** [comment]
Hi

Answer:

- `studio create ferri-sutanto/simfoni-core`
- studio version 0.11.0

Hope its helps :)

Thanks

**Comment by franzliedke** [comment]
Sorry for taking so long... I cannot reproduce this, although I tried to match your setup as exactly as possible.

Are you still having this problem?

**Comment by ghprod** [comment]
Hi, no probs, finally i create package manually :)

Thanks

**Comment by Machecek** [comment]
I have run into the same problem. Any ideas how to overcome it other than creating package manually?
