### ISSUE TITLE
studio create -> Namespace contains / (forward slash)

### ISSUE THREAD

**Issue by seb-ster** [franzliedke/studio#70]
Great Package!
But after following the initial tutorial from the README, the package namespace (Example.php) contains / (forward slahes) as separator.
Also the autoload_static.php arrays contain forward slashes.
After i fixed this, my package worked.

Studio 0.11.1
Windows 10
Apache 2.4.23
PHP 5.6.25
Composer 1.2.2

**Comment by seb-ster** [comment]
Tried it again with a new Package. It appears that i made a Typo on the first one. `studio create` worked correct on the second package.

But it might be a nice feature to atomatically correct forward slahes in the namespace.

**Comment by tomicakorac** [comment]
@seb-ster can you please close your issue if it's been resolved?

**Comment by seb-ster** [comment]
I would like to keep it open as a request for a feature. Or as an issue of
validating user input?

**Comment by franzliedke** [comment]
Released as part of [version 0.11.2](https://github.com/franzliedke/studio/releases/tag/0.11.2).

I guess we could improve the [regex that validates namespace names](https://github.com/franzliedke/studio/blob/c1359ff9fdec24ca4e3ceb5dd38e09ce9ba8b2db/src/Parts/Composer/Part.php#L22) - if any of you want to send a pull request, that would be very cool. :)
