### ISSUE TITLE
Still uses original non–local source with studio set up

### ISSUE THREAD

**Issue by Rarst** [franzliedke/studio#75]
Following install instructions, `studio` installed globally:

```
C:\server\www\composer>studio load c:/server/www/seam
[OK] Packages matching the path c:/server/www/seam will now be loaded by Composer.

C:\server\www\composer>composer update rarst/seam --no-dev
[Studio] Loading path c:/server/www/seam
Loading composer repositories with package information
Updating dependencies
Package operations: 1 install, 0 updates, 0 removals
  - Installing rarst/seam (dev-master 43a3148): Cloning 43a31486dd
Writing lock file
Generating optimized autoload files
```

Package clone happens from GitHub and ignores the local setup.

**Comment by Rarst** [comment]
Hm, I seem to have more general problem with `path` repository, which might be underlying issue here...

https://github.com/composer/composer/issues/6436

**Comment by Rarst** [comment]
Yeah, seems it was just Composer not wanting to set up path repo due to underlying and silent dependency conflicts.

**Comment by franzliedke** [comment]
Thanks for researching it. And good luck with your setup. :)
