### ISSUE TITLE
Broken on Composer 1.6.3

### ISSUE THREAD

**Issue by emodric** [franzliedke/studio#85]
Not really sure what is happening, but as soon as I upgrade to Composer 1.6.3, all my symlinks are gone and real packages are installed instead.

Downgrading to 1.6.2 fixes the issue.

Tested both `master` and `next` branches.

**Comment by franzliedke** [comment]
Thanks for the report - though not sure whether we can do something about this, or whether it's a Composer regression.

I am digging through the Composer changelog, though. Could you please let me know which version of Studio you are using? (Please use `composer global show | grep studio` - I forgot to update the internal version number in one of the latest releases.)

**Comment by franzliedke** [comment]
Also, which operating system are you using?

**Comment by emodric** [comment]
I tested on 0.13 tag as well as `dev-next` and both of those show the regression. OS is Ubuntu 17.10 x64 and PHP is 7.2.2.

**Comment by franzliedke** [comment]
Interesting, I can't replicate the problem on Travis CI, trying both Composer versions: https://travis-ci.org/franzliedke/studio-debug/builds/341929930

Can you please send a pull request to https://github.com/franzliedke/studio-debug to make the library setup more similar to yours? Maybe it has to do with a specific version constraint...

**Comment by emodric** [comment]
I'm using studio as a dev dependency in my project (instead of the global require), so the PR is a bit hacky solution to achieve that, but it shows the difference between 1.6.2 and 1.6.3 on my local machine.

https://github.com/franzliedke/studio-debug/pull/1

1.6.2 installs the libs with symlinks, while 1.6.3 fails altogether (no install from source). I hope Travis will show the same :)

**Comment by emodric** [comment]
@franzliedke Check this out: https://github.com/composer/composer/issues/7127 Looks like a cause of our issue, too.

**Comment by franzliedke** [comment]
@emodric Thanks for letting me know. I will check it out when I get back from my vacation (next week). ;)

**Comment by emodric** [comment]
No worries, enjoy your vacation!

**Comment by franzliedke** [comment]
Sometimes sitting it out helps as well... do you still have this problem on Composer 1.6.4?

**Comment by emodric** [comment]
It looks like it's working fine :) :+1:

**Comment by franzliedke** [comment]
Great. Thanks for all your efforts!
