### ISSUE TITLE
Package from existing directory

### ISSUE THREAD

**Issue by jasonlewis** [franzliedke/studio#9]
Any chance of being able to add a package from an existing directory instead of having to create from scratch?

Handy tool by the way. I think I remember seeing on Twitter that Frank and a couple others were working on something similar? Is that still happening?

**Comment by franzliedke** [comment]
Very good idea, Jason - thank you.

The league only has a skeleton package, no generator package or Composer integration.
As far as I know, @assertchris is working on something similar, but it doesn't yet seem to be as far as this package. I'm still hoping he wants to help me out with this one.

Anyway, I'll work on this right now. Thanks for the input.

**Comment by franzliedke** [comment]
What should this command be called? I think I'll go with `load` for now. Any other ideas?

**Comment by franzliedke** [comment]
This is now available as `studio load` in the just-released [0.9.4 release](https://github.com/franzliedke/studio/releases/tag/0.9.4) - please try it out. =)

**Comment by jasonlewis** [comment]
Awesome, great stuff Franz! Will give it a run when I can.
