### ISSUE TITLE
Package `autoload-dev` not being mapped in Composer's autoload.

### ISSUE THREAD

**Issue by trip-somers** [franzliedke/studio#92]
I'm working with a package for Laravel and trying to run its tests. I have my package installed and properly mapped in a `workbench/{vendor}/{package}` structure. The classes designated via "classmap" and "psr-4" in the `autoload` section are being mapped by Composer's autoload, but nothing from my package's `autoload-dev` section is being mapped.

`autoload-dev` _is_ working for the root Laravel `composer.json` file.

I'm looking for any possible feedback on this. I've tried all kinds of ways around this, and I can't figure it out.

**Comment by trip-somers** [comment]
Okay, so it's pretty clear that Composer won't install every package's dev dependencies, only the main project's dev dependencies. The reason for this is obvious to me now, only minutes after posting the above.

So my question kind of hangs out there, though... how should PHPUnit be run in a Studio environment?

**Comment by franzliedke** [comment]
You're right, dev dependencies are only loaded for the root project.

Since Studio symlinks libraries from their local origin, it assumes you install those libraries' dev-dependencies in their own folder (where you develop the library).

I hope that makes sense. :)
