### ISSUE TITLE
PHP 7.4: Parse error: syntax error, unexpected 'fn'

### ISSUE THREAD

**Issue by rask** [franzliedke/studio#95]
This comes from a dependency called `nikic/iter` it seems.

    $ studio load ../packages/framework
    
    Parse error: syntax error, unexpected 'fn' (T_FN), expecting identifier (T_STRING) in /home/ojrask/.config/composer/vendor/nikic/iter/src/iter.fn.php on line 3

nikic/iter was upgraded so updating the dependency version will probably fix it here as well: https://github.com/nikic/iter/releases/tag/v2.0.0

Happening on studio 0.13.0.

There are other PHP 7.4 errors when using studio, but we can tackle those in other issues.

**Comment by franzliedke** [comment]
Hey, thanks for the report and sorry for the slow response!

nikic/iter isn't part of Studio's (transitive) dependencies, as far as I can tell. It looks like it is installed in your global Composer's dependencies, though - probably by some other global Composer package?

This command should tell you where it comes from:

    composer global why nikic/iter

Closing for now...

**Comment by rask** [comment]
I see, will try digging to see where it appears. Thanks!
