### ISSUE TITLE
Unload does not work

### ISSUE THREAD

**Issue by benjivm** [franzliedke/studio#99]
Composer version: 1.9.1
PHP version: 7.4
OS: Windows 10

I have been working on my package I want to now unload it to switch to the main repo.

```
$ studio unload ~/path/to/proj

[OK] Packages matching the path /path/to/proj will no longer be loaded by Composer.

$ composer update
[Studio] Loading path: /path/to/proj
Loading composer repositories with package information
Updating dependencies (including require-dev)
```

**Comment by benjivm** [comment]
Fixed it, the paths have to be identical (was actually adding a trailing /).

It would be helpful if studio would throw an error if a matching path wasn't found in the links it is monitoring.

**Comment by rask** [comment]
Looks like some path normalization should be in place. So the problem exactly is that `unload` does not remove the entry from `studio.json` properly?
